language: node_js
sudo: false
node_js:
  - "8.11.2"
install:
  - npm install
cache:
  directories:
  - "$HOME/.npm"
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure:
  app: 
    develop: 
after_success: npm run coverage

